#!/system/bin/sh

. /data/adb/modules/nas_photos_mount/cgi-lib.sh
require_auth
[ "$REQUEST_METHOD" = 'GET' ] || fail_json '405 Method Not Allowed' 'method_not_allowed'

path=''
old_ifs=$IFS
IFS='&'
set -- ${QUERY_STRING:-}
IFS=$old_ifs
for pair in "$@"; do
  key=${pair%%=*}
  encoded=${pair#*=}
  [ "$key" = path ] && path=$(decode_form_value "$encoded")
done

if [ -n "$path" ]; then
  valid_remote_path "$path" || fail_json '400 Bad Request' 'invalid_remote_path'
fi

export LD_LIBRARY_PATH="$MODDIR"
temp_json="$STATE_DIR/browse.json.$$"
if timeout 20 "$RCLONE" lsjson "nas:$path" \
  --config "$CONFIG" \
  --dirs-only \
  --max-depth 1 \
  --no-mimetype \
  --no-modtime \
  > "$temp_json" 2>> "$LOG"; then
  send_json_header
  "$BUSYBOX" cat "$temp_json"
  rm -f "$temp_json"
else
  rm -f "$temp_json"
  fail_json '502 Bad Gateway' 'browse_failed'
fi
